name: generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake animation (dark theme)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=00f5d4&color_dots=#0d1117,#161b22,#0e4429,#006d32,#26a641,#39d353
            dist/github-contribution-grid-snake-dark.svg?color_snake=00f5d4&color_dots=#0d1117,#161b22,#0e4429,#006d32,#26a641,#39d353

      - name: push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
